#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pyyaml",
# ]
# ///
"""Extract llms.txt entries that are NOT present in the curated copilot-excerpt.md.

check_copilot_excerpt.py only verifies that copilot-excerpt.md's existing titles/URLs
still match the source llms.txt (path defined in config.yml) -- it does not say
anything about whether the *scope* of the curation is right. This script produces
the raw material for that harder question: every source entry whose URL is absent
from the excerpt, split into two groups by the same keyword heuristic
check_copilot_excerpt.py already uses for its "POSSIBLE ADDITIONS" hint
(CANDIDATE_KEYWORDS / looks_candidate):

  - uncurated_agent_candidates.md -- entries the heuristic thinks are Copilot/AI-ish
  - uncurated_non_candidates.md   -- everything else not in the excerpt

Each entry keeps its source `## Section` heading so a reader (human or LLM) has the
same context the source llms.txt gives.

These two files are meant to be read next by verify_agent_relevance.py, which asks
an AI model for a natural-language second opinion on both lists. This script itself
makes no relevance judgement beyond the existing keyword heuristic.

This script imports check_copilot_excerpt.py, which depends on PyYAML -- run it via
`uv run extract_uncurated_entries.py`, not bare `python`.

Usage: uv run extract_uncurated_entries.py [--excerpt PATH] [--source PATH] [--out-dir PATH]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import check_copilot_excerpt as base

SKILL_DIR = Path(__file__).resolve().parent
DEFAULT_OUT_DIR = SKILL_DIR / "output" / "verification"

SECTION_RE = re.compile(r"^##\s+(.*)$")

GENERATED_HEADER = (
    "<!-- Generated by extract_uncurated_entries.py -- do not hand-edit.\n"
    "     Re-run the script to refresh. Consumed by verify_agent_relevance.py. -->\n\n"
)


def parse_entries_with_section(text: str) -> list[dict]:
    entries = []
    section = None
    for line in text.splitlines():
        stripped = line.strip()
        heading = SECTION_RE.match(stripped)
        if heading:
            section = heading.group(1).strip()
            continue
        match = base.ENTRY_RE.match(stripped)
        if match:
            entry = match.groupdict()
            entry["section"] = section or "(no section)"
            entries.append(entry)
    return entries


def format_entries(entries: list[dict]) -> str:
    lines: list[str] = []
    current_section = None
    for entry in entries:
        if entry["section"] != current_section:
            if lines:
                lines.append("")
            lines.append(f"## {entry['section']}")
            lines.append("")
            current_section = entry["section"]
        lines.append(f"- [{entry['title']}]({entry['url']}): {entry['desc']}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--excerpt", type=Path, default=base.DEFAULT_EXCERPT)
    parser.add_argument("--source", type=Path, default=base.DEFAULT_SOURCE)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args()

    if not args.source.is_file():
        print(f"ERROR: source file not found: {args.source}", file=sys.stderr)
        return 2
    if not args.excerpt.is_file():
        print(f"ERROR: excerpt file not found: {args.excerpt}", file=sys.stderr)
        return 2

    source_entries = parse_entries_with_section(args.source.read_text(encoding="utf-8"))
    excerpt_urls = {e["url"] for e in base.parse_entries(args.excerpt.read_text(encoding="utf-8"))}

    uncurated = [e for e in source_entries if e["url"] not in excerpt_urls]
    agent_candidates = [e for e in uncurated if base.looks_candidate(e)]
    non_candidates = [e for e in uncurated if not base.looks_candidate(e)]

    args.out_dir.mkdir(parents=True, exist_ok=True)
    candidates_path = args.out_dir / "uncurated_agent_candidates.md"
    non_candidates_path = args.out_dir / "uncurated_non_candidates.md"

    candidates_path.write_text(
        GENERATED_HEADER + format_entries(agent_candidates), encoding="utf-8"
    )
    non_candidates_path.write_text(
        GENERATED_HEADER + format_entries(non_candidates), encoding="utf-8"
    )

    print(f"Checked {len(source_entries)} source entries against {len(excerpt_urls)} excerpt URLs.")
    print(f"Uncurated (not in excerpt): {len(uncurated)}")
    print(f"  agent-candidate (keyword heuristic): {len(agent_candidates)} -> {candidates_path}")
    print(f"  non-candidate:                       {len(non_candidates)} -> {non_candidates_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
