# `.github/workflows/pr-agent.yml` で利用する PR Agent の設定ファイル
# https://docs.pr-agent.ai/usage-guide/configuration_options/#local-configuration-file
# 使用可能設定は https://github.com/the-pr-agent/pr-agent/blob/main/pr_agent/settings/configuration.toml を参照

[config]
model="gpt-5.6-luna"