"""Copy-and-adapt template: validate an AI-generated llms.txt excerpt against its source.

Copy this file into a new skill's directory (next to the excerpt generated by
generate_llms_excerpt.py) and adjust the DEFAULT_* constants and
CANDIDATE_KEYWORDS below.

The excerpt is a structured subset of the source llms.txt: every entry is a
`- [Title](URL): description` line copied verbatim from the source. Because
the source is re-downloaded periodically, and because the excerpt was
originally produced from an LLM draft, entries can drift or be wrong. This
script cross-checks every excerpt entry against the source by URL (the more
stable key) and reports:

  MALFORMED  a body line starts with "- " but does not parse as an entry
             (broken markdown emitted by the AI, or a hand-edit typo)
  MISSING    the excerpt's URL no longer exists in the source llms.txt
  TITLE      the URL exists in the source but under a different title
  DESC       URL/title match but the description drifted (informational)
  STALE      the source was re-fetched after the excerpt was generated
             (informational; regenerate or re-check after big upstream changes)

If CANDIDATE_KEYWORDS is non-empty, it also lists source entries matching
those keywords that are absent from the excerpt, as candidates a human should
consider adding -- a heuristic hint, not a re-run of the curation judgment.

Fix reported problems by editing the excerpt file directly (align the title
with the source, delete MISSING lines, repair MALFORMED lines) and re-run this
script. Do NOT re-run the AI model to fix them: regeneration is
nondeterministic and can break other entries, while this output already
pinpoints exactly what to fix.

Usage: python check_llms_excerpt.py [--excerpt PATH] [--source PATH]
Exit code: 1 if any MALFORMED, MISSING or TITLE mismatch is found, 0 otherwise,
2 on usage errors (file not found etc.).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# --- adapt these constants when copying into a new skill ---------------------
SKILL_DIR = Path(__file__).resolve().parent
DEFAULT_EXCERPT = SKILL_DIR / "output" / "excerpt.md"
DEFAULT_SOURCE = SKILL_DIR / "output" / "llms.txt"
# Lowercase keywords marking source entries that look relevant to this skill
# (e.g. ("copilot", "agent", "mcp")). Leave empty to skip the candidate hint.
CANDIDATE_KEYWORDS: tuple[str, ...] = ()
# ------------------------------------------------------------------------------

# Keep in sync with generate_llms_excerpt.py's ENTRY_RE.
ENTRY_RE = re.compile(r"^- \[(?P<title>[^\]]+)\]\((?P<url>\S+)\)(?::\s*(?P<desc>.*))?$")
FETCHED_AT_RE = re.compile(r"^fetched_at:\s*(\S+)", re.MULTILINE)
EXTRACTED_AT_RE = re.compile(r"^extracted_from_fetched_at:\s*(\S+)", re.MULTILINE)


def strip_frontmatter(text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return "\n".join(lines[i + 1 :])
    return text


def parse_entries(text: str) -> tuple[list[dict], list[str]]:
    """Return (entries, malformed_lines) from the body of an index/excerpt file."""
    entries = []
    malformed = []
    for line in strip_frontmatter(text).splitlines():
        stripped = line.strip()
        match = ENTRY_RE.match(stripped)
        if match:
            entry = match.groupdict()
            entry["desc"] = entry["desc"] or ""
            entries.append(entry)
        elif stripped.startswith("- "):
            malformed.append(stripped)
    return entries, malformed


def looks_candidate(entry: dict) -> bool:
    haystack = f"{entry['title']} {entry['url']} {entry['desc']}".lower()
    return any(keyword in haystack for keyword in CANDIDATE_KEYWORDS)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--excerpt", type=Path, default=DEFAULT_EXCERPT)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    args = parser.parse_args()

    if not args.source.is_file():
        print(f"ERROR: source file not found: {args.source}", file=sys.stderr)
        print("Run this skill's download script first.", file=sys.stderr)
        return 2
    if not args.excerpt.is_file():
        print(f"ERROR: excerpt file not found: {args.excerpt}", file=sys.stderr)
        print("Run generate_llms_excerpt.py (adapted copy) first.", file=sys.stderr)
        return 2

    excerpt_text = args.excerpt.read_text(encoding="utf-8")
    source_text = args.source.read_text(encoding="utf-8")

    excerpt_entries, malformed = parse_entries(excerpt_text)
    source_entries, _ = parse_entries(source_text)
    source_by_url = {e["url"]: e for e in source_entries}
    excerpt_urls = {e["url"] for e in excerpt_entries}

    missing = []
    title_mismatches = []
    desc_drift = []

    for entry in excerpt_entries:
        source_entry = source_by_url.get(entry["url"])
        if source_entry is None:
            missing.append(entry)
            continue
        if source_entry["title"] != entry["title"]:
            title_mismatches.append((entry, source_entry))
        elif source_entry["desc"] != entry["desc"]:
            desc_drift.append((entry, source_entry))

    candidates = [
        e
        for e in source_entries
        if CANDIDATE_KEYWORDS and e["url"] not in excerpt_urls and looks_candidate(e)
    ]

    print(
        f"Checked {len(excerpt_entries)} excerpt entries against {len(source_entries)} source entries.\n"
    )

    if malformed:
        print(
            f"MALFORMED ({len(malformed)}) -- body lines starting with '- ' that do not parse as `- [Title](URL)` entries:"
        )
        for line in malformed:
            print(f"  - {line}")
        print()

    if missing:
        print(
            f"MISSING ({len(missing)}) -- excerpt URL not found in source llms.txt (renamed/removed upstream, or never existed):"
        )
        for e in missing:
            print(f"  - [{e['title']}]({e['url']})")
        print()

    if title_mismatches:
        print(
            f"TITLE MISMATCH ({len(title_mismatches)}) -- URL exists in source under a different title:"
        )
        for excerpt_e, source_e in title_mismatches:
            print(f"  - excerpt: [{excerpt_e['title']}]({excerpt_e['url']})")
            print(f"    source:  [{source_e['title']}]({source_e['url']})")
        print()

    if desc_drift:
        print(
            f"DESCRIPTION DRIFT ({len(desc_drift)}, informational only) -- title/URL match but description text changed upstream:"
        )
        for excerpt_e, source_e in desc_drift:
            print(f"  - [{excerpt_e['title']}]({excerpt_e['url']})")
            print(f"    excerpt: {excerpt_e['desc']}")
            print(f"    source:  {source_e['desc']}")
        print()

    source_fetched = FETCHED_AT_RE.search(source_text)
    excerpt_extracted = EXTRACTED_AT_RE.search(excerpt_text)
    if (
        source_fetched
        and excerpt_extracted
        and source_fetched.group(1) != excerpt_extracted.group(1)
    ):
        print(
            "STALE (informational only) -- the source was re-fetched after this excerpt was generated:\n"
            f"  excerpt extracted_from_fetched_at: {excerpt_extracted.group(1)}\n"
            f"  source fetched_at:                 {source_fetched.group(1)}\n"
        )

    if candidates:
        print(
            f"POSSIBLE ADDITIONS ({len(candidates)}, informational only) -- source entries matching CANDIDATE_KEYWORDS but not in the excerpt; review manually, this is a keyword heuristic, not a re-curation:"
        )
        for e in candidates:
            print(f"  - [{e['title']}]({e['url']}): {e['desc']}")
        print()

    if not malformed and not missing and not title_mismatches:
        print("OK: excerpt format is valid and every title/URL matches the source llms.txt.")

    return 1 if (malformed or missing or title_mismatches) else 0


if __name__ == "__main__":
    raise SystemExit(main())
