"""Generate a YAML summary of `claude --help` output.

Claude Code's `--help` is generated by commander.js (Node.js), which uses a
different layout from Codex CLI's clap (Rust) style help:

- `Usage:` is a single line.
- `Arguments:` / `Options:` / `Commands:` entries all share the same shape: a
  2-space-indented header line with the name, followed either by an inline
  description on the same line (separated from the name by a run of 2+
  spaces) or — when the name is too long to fit — by description lines on the
  following lines. Wrapped descriptions are indented deeper than the header
  (aligned to the shared description column, or a fixed deeper indent for
  overlong flag names). The parser joins these description lines with a
  single space into one `description`.

The output YAML records a `fetched_at` timestamp. On rerun, generation is
skipped if the existing output was fetched within the last 24 hours; pass
--force to regenerate regardless of age.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path

import yaml

SKILL_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT = SKILL_DIR / "output" / "help_result.yaml"

SPLIT_RE = re.compile(r" {2,}")
SECTION_HEADERS = ("Arguments:", "Options:", "Commands:")
# commander.js では全セクションのエントリのヘッダ行がインデント2。
# これより深いインデントの行は、直前エントリの説明の続行とみなす。
ENTRY_HEADER_INDENT_MAX = 2
FRESHNESS = timedelta(days=1)


def read_fetched_at(path: Path) -> datetime | None:
    if not path.is_file():
        return None
    try:
        with path.open(encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError:
        return None
    if not isinstance(data, dict):
        return None
    value = data.get("fetched_at")
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def run_claude(*args: str) -> str:
    executable = shutil.which("claude") or "claude"
    result = subprocess.run(
        [executable, *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=True,
    )
    return result.stdout


def split_entry(text: str) -> tuple[str, str]:
    parts = SPLIT_RE.split(text, maxsplit=1)
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    return parts[0].strip(), ""


def parse_entry_section(lines: list[str]) -> list[dict[str, str]]:
    """Arguments:/Options:/Commands: entries are `name<2+ spaces>description` header lines plus deeper-indented continuation lines."""
    entries: list[dict[str, str]] = []
    for line in lines:
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(" "))
        text = line.strip()
        # 「Examples:」のような「単語1つで `:` 終わり」の行はエントリ名ではなく、
        # 直前エントリにぶら下がる説明ブロックの見出し（フラグ・コマンド名は `:` で終わらない）。
        # 説明文が `:` で終わる正当なヘッダ（例: "Input format (only works with --print):"）と区別するため単語1つに限定する。
        is_bare_label = text.endswith(":") and " " not in text
        is_header = indent <= ENTRY_HEADER_INDENT_MAX and (not is_bare_label or not entries)
        if is_header:
            name, description = split_entry(text)
            entries.append({"name": name, "description": description})
        elif entries:
            entries[-1]["description"] = (entries[-1]["description"] + " " + text).strip()
    return entries


def parse_help(help_text: str) -> dict:
    usage: list[str] = []
    description_lines: list[str] = []
    sections: dict[str, list[str]] = {name: [] for name in SECTION_HEADERS}
    current_section: str | None = None
    in_usage = False

    for line in help_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("Usage:"):
            usage.append(stripped[len("Usage:") :].strip())
            current_section = None
            in_usage = True
            continue
        if stripped in SECTION_HEADERS:
            current_section = stripped
            in_usage = False
            continue
        if in_usage:
            if stripped:
                usage.append(stripped)
            else:
                in_usage = False
            continue
        if current_section is not None:
            sections[current_section].append(line)
        elif stripped:
            description_lines.append(stripped)

    return {
        "usage": usage,
        "description": " ".join(description_lines).strip(),
        "commands": parse_entry_section(sections["Commands:"]),
        "arguments": parse_entry_section(sections["Arguments:"]),
        "options": parse_entry_section(sections["Options:"]),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--help-file",
        type=Path,
        help="Parse a previously captured `claude --help` output instead of invoking claude.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"YAML output path (default: {DEFAULT_OUTPUT.relative_to(SKILL_DIR)})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate even if the existing output was fetched less than a day ago.",
    )
    args = parser.parse_args()

    if not args.force:
        fetched_at = read_fetched_at(args.output)
        if fetched_at is not None and datetime.now(timezone.utc) - fetched_at < FRESHNESS:
            print(
                f"{args.output}: すでに最新が取得済です（取得時刻: {fetched_at.isoformat()}）。--force で上書きできます。"
            )
            return

    version = run_claude("--version").splitlines()[0].strip()
    help_text = (
        args.help_file.read_text(encoding="utf-8") if args.help_file else run_claude("--help")
    )

    fetched_at_now = datetime.now(timezone.utc).isoformat()
    data = {"version": version, "fetched_at": fetched_at_now, **parse_help(help_text)}

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as f:
        yaml.dump(
            data, f, allow_unicode=True, sort_keys=False, default_flow_style=False, width=100000
        )

    try:
        display_path = args.output.resolve().relative_to(SKILL_DIR)
    except ValueError:
        display_path = args.output
    print(f"Wrote {display_path}")


if __name__ == "__main__":
    main()
