"""Regenerate README.md's "AIツールごとの設定・プラグインルート" section from
the `readme` block of each tool entry in ai-tools.yaml.

The section is replaced in-place between the `<!-- BEGIN: ai-tools-section -->`
/ `<!-- END: ai-tools-section -->` markers, which must already exist in
README.md (this script does not insert them).
"""

from __future__ import annotations

import sys
from typing import Any

from plugin_meta.util.ai_tools_config import REPO_ROOT, load_config

README_PATH = REPO_ROOT / "README.md"
BEGIN_MARKER = "<!-- BEGIN: ai-tools-section -->"
END_MARKER = "<!-- END: ai-tools-section -->"

DISPLAY_NAMES = {
    "claude-code": "Claude Code",
    "cline": "Cline",
    "codex": "Codex",
    "copilot": "GitHub Copilot",
    "cursor": "Cursor",
    "antigravity": "Antigravity",
}

SECTION_INTRO = (
    "各 AI コーディングツール向けの設定フォルダとプラグイン実体フォルダの対応。  \n"
    "同一ツールでも「ツールが読む設定（`.` 始まり）」と「プラグイン実体（`*-plugins/`）」が分かれていることがある。"
)


def build_tool_block(tool_key: str, tool: dict[str, Any]) -> list[str]:
    lines = [f"- **{DISPLAY_NAMES[tool_key]}**"]
    for entries in tool["readme"].values():
        for entry in entries:
            path = entry["path"]
            lines.append(f"  - [{path}/]({path}/) — {entry['description']}")
    return lines


def build_section(config: dict[str, Any]) -> str:
    lines = [
        BEGIN_MARKER,
        "<!-- Generated by tools/internal/plugin_meta/generate/generate_readme_tools_section.py (DO NOT EDIT MANUALLY) -->",
        "",
        "### AIツールごとの設定・プラグインルート",
        "",
        SECTION_INTRO,
        "",
    ]

    tool_blocks = [
        build_tool_block(tool_key, tool)
        for tool_key, tool in config["tools"].items()
        if "readme" in tool
    ]
    for i, block in enumerate(tool_blocks):
        lines.extend(block)
        if i != len(tool_blocks) - 1:
            lines.append("")

    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def replace_section(readme_text: str, section: str) -> str:
    begin_idx = readme_text.index(BEGIN_MARKER)
    end_idx = readme_text.index(END_MARKER) + len(END_MARKER)
    return readme_text[:begin_idx] + section + readme_text[end_idx:]


def main() -> None:
    readme_text = README_PATH.read_text(encoding="utf-8")
    if BEGIN_MARKER not in readme_text or END_MARKER not in readme_text:
        sys.exit(
            f"{README_PATH} is missing the {BEGIN_MARKER}/{END_MARKER} marker pair; add it first"
        )

    config = load_config()
    section = build_section(config)
    README_PATH.write_text(replace_section(readme_text, section), encoding="utf-8")
    print(f"Wrote {README_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
