"""Regenerate CATALOG.md for every plugin's skill folder listed in ai-tools.yaml.

For each plugin across every tool, resolves its skill root according to its
skills_layout ("subdir" -> <plugin>/skills, "direct" -> <plugin> itself) and
writes a CATALOG.md there listing its immediate subfolders that contain a
SKILL.md, with that file's raw frontmatter block concatenated in.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from plugin_meta.util.ai_tools_config import REPO_ROOT, load_config
from skill.util.skill_frontmatter import read_frontmatter


def has_skill_subdir(skills_dir: Path) -> bool:
    return any(
        sub_dir.is_dir() and (sub_dir / "SKILL.md").is_file() for sub_dir in skills_dir.iterdir()
    )


def find_skills_dirs(config: dict[str, Any]) -> list[Path]:
    skills_dirs = set()
    for tool in config["tools"].values():
        for plugin in tool.get("plugins", []):
            plugin_dir = REPO_ROOT / plugin["path"]
            skills_dir = (
                plugin_dir / "skills" if plugin["skills_layout"] == "subdir" else plugin_dir
            )
            if skills_dir.is_dir() and has_skill_subdir(skills_dir):
                skills_dirs.add(skills_dir)
    return sorted(skills_dirs)


def build_catalog(skills_dir: Path) -> str:
    entries = []
    for sub_dir in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
        skill_md_path = sub_dir / "SKILL.md"
        if not skill_md_path.is_file():
            continue
        frontmatter = read_frontmatter(skill_md_path)
        if frontmatter is None:
            print(
                f"warning: skipping {skill_md_path.relative_to(REPO_ROOT)} (no valid frontmatter)",
                file=sys.stderr,
            )
            continue
        entries.append((sub_dir.name, frontmatter.raw.strip("\n")))

    lines = [
        "<!-- Generated by tools/internal/plugin_meta/generate/generate_skills_catalog_md.py (DO NOT EDIT MANUALLY) -->",
        "",
    ]
    for name, raw in entries:
        lines.append(f"- {name}")
        lines.append("---")
        lines.append(raw)
        lines.append("---")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> None:
    config = load_config()
    skills_dirs = find_skills_dirs(config)
    if not skills_dirs:
        sys.exit("no skills/ directories found")

    for skills_dir in skills_dirs:
        catalog_path = skills_dir / "CATALOG.md"
        catalog_path.write_text(build_catalog(skills_dir), encoding="utf-8")
        print(f"Wrote {catalog_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
