"""Generate a YAML summary of `codex --help` output.

Codex's `--help` is generated by clap (Rust), which uses a different layout
from Copilot CLI's click-style help:

- `Usage:` can span multiple lines (continuation lines are indented to align
  with the first line's command text).
- `Commands:` entries are single-line: a 2-space-indented name followed by a
  run of 2+ spaces and a description, same shape as Copilot CLI.
- `Arguments:` and `Options:` entries are two-line-or-more: a header line
  (indent <= 6, e.g. `  -c, --config <key=value>` or `      --enable
  <FEATURE>`) with no inline description, followed by one or more
  description lines indented further (typically 10 spaces). Blank lines
  inside a description (paragraph breaks, `Possible values:` lists, etc.)
  are dropped and the remaining lines are joined with a single space.

The output YAML records a `fetched_at` timestamp. On rerun, generation is
skipped if the existing output was fetched within the last 24 hours; pass
--force to regenerate regardless of age.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path

import yaml

SKILL_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT = SKILL_DIR / "output" / "help_result.yaml"

SPLIT_RE = re.compile(r" {2,}")
SECTION_HEADERS = ("Commands:", "Arguments:", "Options:")
FLAG_HEADER_INDENT_MAX = 6
FRESHNESS = timedelta(days=1)


def read_fetched_at(path: Path) -> datetime | None:
    if not path.is_file():
        return None
    try:
        with path.open(encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError:
        return None
    if not isinstance(data, dict):
        return None
    value = data.get("fetched_at")
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def run_codex(*args: str) -> str:
    executable = shutil.which("codex") or "codex"
    result = subprocess.run(
        [executable, *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=True,
    )
    return result.stdout


def split_entry(text: str) -> tuple[str, str]:
    parts = SPLIT_RE.split(text, maxsplit=1)
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    return parts[0].strip(), ""


def parse_command_section(lines: list[str]) -> list[dict[str, str]]:
    """Commands: entries are single-line `name<2+ spaces>description`."""
    entries: list[dict[str, str]] = []
    for line in lines:
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(" "))
        text = line.strip()
        if indent <= 2:
            name, description = split_entry(text)
            entries.append({"name": name, "description": description})
        elif entries:
            entries[-1]["description"] = (entries[-1]["description"] + " " + text).strip()
    return entries


def parse_flag_section(lines: list[str]) -> list[dict[str, str]]:
    """Arguments:/Options: entries are a header line plus indented description lines."""
    entries: list[dict[str, str]] = []
    for line in lines:
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(" "))
        text = line.strip()
        if indent <= FLAG_HEADER_INDENT_MAX:
            entries.append({"name": text, "description": ""})
        elif entries:
            entries[-1]["description"] = (entries[-1]["description"] + " " + text).strip()
    return entries


def parse_help(help_text: str) -> dict:
    usage: list[str] = []
    description_lines: list[str] = []
    sections: dict[str, list[str]] = {name: [] for name in SECTION_HEADERS}
    current_section: str | None = None
    in_usage = False

    for line in help_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("Usage:"):
            usage.append(stripped[len("Usage:") :].strip())
            current_section = None
            in_usage = True
            continue
        if stripped in SECTION_HEADERS:
            current_section = stripped
            in_usage = False
            continue
        if in_usage:
            if stripped:
                usage.append(stripped)
            else:
                in_usage = False
            continue
        if current_section is not None:
            sections[current_section].append(line)
        elif stripped:
            description_lines.append(stripped)

    return {
        "usage": usage,
        "description": " ".join(description_lines).strip(),
        "commands": parse_command_section(sections["Commands:"]),
        "arguments": parse_flag_section(sections["Arguments:"]),
        "options": parse_flag_section(sections["Options:"]),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--help-file",
        type=Path,
        help="Parse a previously captured `codex --help` output instead of invoking codex.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"YAML output path (default: {DEFAULT_OUTPUT.relative_to(SKILL_DIR)})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate even if the existing output was fetched less than a day ago.",
    )
    args = parser.parse_args()

    if not args.force:
        fetched_at = read_fetched_at(args.output)
        if fetched_at is not None and datetime.now(timezone.utc) - fetched_at < FRESHNESS:
            print(
                f"{args.output}: すでに最新が取得済です（取得時刻: {fetched_at.isoformat()}）。--force で上書きできます。"
            )
            return

    version = run_codex("--version").splitlines()[0].strip()
    help_text = (
        args.help_file.read_text(encoding="utf-8") if args.help_file else run_codex("--help")
    )

    fetched_at_now = datetime.now(timezone.utc).isoformat()
    data = {"version": version, "fetched_at": fetched_at_now, **parse_help(help_text)}

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as f:
        yaml.dump(
            data, f, allow_unicode=True, sort_keys=False, default_flow_style=False, width=100000
        )

    try:
        display_path = args.output.resolve().relative_to(SKILL_DIR)
    except ValueError:
        display_path = args.output
    print(f"Wrote {display_path}")


if __name__ == "__main__":
    main()
